<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['base_category_cloud'] = 'Cloud';
$lang['base_category_gateway'] = 'Passerelle';
$lang['base_category_network'] = 'Réseau';
$lang['base_category_reports'] = 'Rapports';
$lang['base_category_server'] = 'Serveur';
$lang['base_category_spotlight'] = 'Projecteur';
$lang['base_category_system'] = 'Système';
$lang['base_subcategory_account_manager'] = 'Gestionnaire de comptes';
$lang['base_subcategory_accounts'] = 'Comptes';
$lang['base_subcategory_antimalware'] = 'Antipourriels';
$lang['base_subcategory_applications'] = 'Applications';
$lang['base_subcategory_backup'] = 'Sauvegarde';
$lang['base_subcategory_bandwidth_control'] = 'Bandwidth Control';
$lang['base_subcategory_base'] = 'Base';
$lang['base_subcategory_communication_and_collaboration'] = 'Communication and Collaboration';
$lang['base_subcategory_configuration'] = 'Configuration';
$lang['base_subcategory_content_filter_and_proxy'] = 'Proxy et filtrage';
$lang['base_subcategory_content_management_systems'] = 'Content Management Systems';
$lang['base_subcategory_database'] = 'Base de données';
$lang['base_subcategory_device_management'] = 'Device Management';
$lang['base_subcategory_directory'] = 'Répertoire';
$lang['base_subcategory_file'] = 'Fichier';
$lang['base_subcategory_filtering'] = 'Filtrage';
$lang['base_subcategory_firewall'] = 'Pare-feu';
$lang['base_subcategory_infrastructure'] = 'Infrastructure';
$lang['base_subcategory_intrusion_protection'] = 'Protection d\'intrusions';
$lang['base_subcategory_mail'] = 'Courrier';
$lang['base_subcategory_messaging'] = 'Messaging';
$lang['base_subcategory_monitoring'] = 'Monitoring';
$lang['base_subcategory_my_account'] = 'Mon compte';
$lang['base_subcategory_network_infrastructure'] = 'Network Infrastructure';
$lang['base_subcategory_performance_and_resources'] = 'Performance and Resources';
$lang['base_subcategory_print'] = 'Impression';
$lang['base_subcategory_protocol_filter'] = 'Filtrage de protocole';
$lang['base_subcategory_resources'] = 'Ressources';
$lang['base_subcategory_security'] = 'Sécurité';
$lang['base_subcategory_services'] = 'Services';
$lang['base_subcategory_settings'] = 'Paramètres';
$lang['base_subcategory_storage'] = 'Stockage';
$lang['base_subcategory_updates'] = 'Updates';
$lang['base_subcategory_user_management'] = 'User Management';
$lang['base_subcategory_vpn'] = 'VPN';
$lang['base_subcategory_web'] = 'Web';
