<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['base_category_cloud'] = 'Cloud';
$lang['base_category_gateway'] = 'Passerelle';
$lang['base_category_my_account'] = 'Mon compte';
$lang['base_category_network'] = 'Réseau';
$lang['base_category_reports'] = 'Rapports';
$lang['base_category_server'] = 'Serveur';
$lang['base_category_spotlight'] = 'Projecteur';
$lang['base_category_system'] = 'Système';
$lang['base_subcategory_accounts'] = 'Comptes';
$lang['base_subcategory_accounts_manager'] = 'Gestionnaire de comptes';
$lang['base_subcategory_antimalware'] = 'Antipourriels';
$lang['base_subcategory_backup'] = 'Sauvegarde';
$lang['base_subcategory_bandwidth_and_qos'] = 'Bande passante et QoS';
$lang['base_subcategory_configuration'] = 'Configuration';
$lang['base_subcategory_content_filter_and_proxy'] = 'Proxy et filtrage';
$lang['base_subcategory_dashboard'] = 'Tableau de bord';
$lang['base_subcategory_database'] = 'Base de données';
$lang['base_subcategory_directory'] = 'Répertoire';
$lang['base_subcategory_file'] = 'Fichier';
$lang['base_subcategory_firewall'] = 'Pare-feu';
$lang['base_subcategory_infrastructure'] = 'Infrastructure';
$lang['base_subcategory_intrusion_protection'] = 'Protection d\'intrusions';
$lang['base_subcategory_mail'] = 'Courrier';
$lang['base_subcategory_mail_scanning'] = 'Analyse de courrier';
$lang['base_subcategory_messaging_and_collaboration'] = 'Messagerie et collaboration';
$lang['base_subcategory_monitoring'] = 'Monitoring';
$lang['base_subcategory_operating_system'] = 'Système d\'exploitation';
$lang['base_subcategory_overview'] = 'Vue d\'ensemble';
$lang['base_subcategory_print'] = 'Impression';
$lang['base_subcategory_protocol_filter'] = 'Filtrage de protocole';
$lang['base_subcategory_resources'] = 'Ressources';
$lang['base_subcategory_security'] = 'Sécurité';
$lang['base_subcategory_settings'] = 'Paramètres';
$lang['base_subcategory_storage'] = 'Stockage';
$lang['base_subcategory_virtualization'] = 'Virtualization';
$lang['base_subcategory_vpn'] = 'VPN';
$lang['base_subcategory_web'] = 'Web';
