<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['base_category_cloud'] = 'Облако';
$lang['base_category_gateway'] = 'Шлюз';
$lang['base_category_network'] = 'Сеть';
$lang['base_category_reports'] = 'Отчеты';
$lang['base_category_server'] = 'Сервер';
$lang['base_category_spotlight'] = 'Spotlight';
$lang['base_category_system'] = 'Система';
$lang['base_subcategory_account_manager'] = 'Менеджер учётной записи';
$lang['base_subcategory_accounts'] = 'Учётная запись';
$lang['base_subcategory_antimalware'] = 'Антивирус';
$lang['base_subcategory_applications'] = 'Applications';
$lang['base_subcategory_backup'] = 'Резервное копирование';
$lang['base_subcategory_bandwidth_control'] = 'Bandwidth Control';
$lang['base_subcategory_base'] = 'Base';
$lang['base_subcategory_communication_and_collaboration'] = 'Communication and Collaboration';
$lang['base_subcategory_configuration'] = 'Конфигурация';
$lang['base_subcategory_content_filter_and_proxy'] = 'Фильтр контента и прокси';
$lang['base_subcategory_content_management_systems'] = 'Content Management Systems';
$lang['base_subcategory_database'] = 'База данных';
$lang['base_subcategory_device_management'] = 'Device Management';
$lang['base_subcategory_directory'] = 'Каталог';
$lang['base_subcategory_file'] = 'Файлы';
$lang['base_subcategory_firewall'] = 'Брандмауэр';
$lang['base_subcategory_filtering'] = 'Filtering';
$lang['base_subcategory_infrastructure'] = 'Инфраструктура';
$lang['base_subcategory_intrusion_protection'] = 'Защита от проникновений';
$lang['base_subcategory_mail'] = 'Почта';
$lang['base_subcategory_messaging'] = 'Messaging';
$lang['base_subcategory_monitoring'] = 'Мониторинг';
$lang['base_subcategory_my_account'] = 'Моя учётная запись';
$lang['base_subcategory_network_infrastructure'] = 'Network Infrastructure';
$lang['base_subcategory_performance_and_resources'] = 'Performance and Resources';
$lang['base_subcategory_print'] = 'Печать';
$lang['base_subcategory_protocol_filter'] = 'Фильтр протокола';
$lang['base_subcategory_resources'] = 'Resources';
$lang['base_subcategory_security'] = 'Безопасность';
$lang['base_subcategory_services'] = 'Services';
$lang['base_subcategory_settings'] = 'Настройки';
$lang['base_subcategory_storage'] = 'Storage';
$lang['base_subcategory_updates'] = 'Updates';
$lang['base_subcategory_user_management'] = 'User Management';
$lang['base_subcategory_vpn'] = 'VPN';
$lang['base_subcategory_web'] = 'Web';
