#!/bin/sh

# Add http caching to yum by default
#-----------------------------------

CHECK=`grep ^http_caching= /etc/yum.conf`

if ( [ -e /etc/yum.conf ] && [ -z "$CHECK" ] ); then
    logger -p local6.notice -t installer "app-base-core - adding httpd_caching to yum"
    sed -i -e "s/\[main\]/\[main\]\nhttp_caching=packages/" /etc/yum.conf
fi

# Set default start/boot
#-----------------------

logger -p local6.notice -t installer "app-base-core - enabling Webconfig server"
chkconfig webconfig on >/dev/null 2>&1

logger -p local6.notice -t installer "app-base-core - starting Webconfig server"
service webconfig start >/dev/null 2>&1

# Anaconda - start clearsync to ensure syncation install_event happens
#---------------------------------------------------------------------

# FIXME: see syncaction review
# /sbin/service clearsyncd restart >/dev/null 2>&1

# Run grub update to capture /etc/release changes on bootstrap
#-------------------------------------------------------------

/usr/sbin/grub2-mkconfig --output=/boot/grub2/grub.cfg >/dev/null 2>&1

# Install wizard flag
#--------------------

touch /var/clearos/base/wizard

# FIXME just a hack for the developer release
echo "AdminLTE = a:5:{s:4:\"menu\";s:1:\"2\";s:3:\"css\";s:9:\"skin-blue\";s:7:\"color_1\";s:0:\"\";s:7:\"color_2\";s:0:\"\";s:7:\"color_3\";s:0:\"\";}\"" > /etc/clearos/webconfig.conf
