#!/bin/sh

# Sudoers
#--------

/usr/sbin/addsudo /bin/cat app-base-core
/usr/sbin/addsudo /bin/chmod app-base-core
/usr/sbin/addsudo /bin/chown app-base-core
/usr/sbin/addsudo /bin/cp app-base-core
/usr/sbin/addsudo /bin/kill app-base-core
/usr/sbin/addsudo /bin/ls app-base-core
/usr/sbin/addsudo /bin/mkdir app-base-core
/usr/sbin/addsudo /bin/mv app-base-core
/usr/sbin/addsudo /bin/rpm app-base-core
/usr/sbin/addsudo /bin/rm app-base-core
/usr/sbin/addsudo /bin/rmdir app-base-core
/usr/sbin/addsudo /bin/touch app-base-core
/usr/sbin/addsudo /sbin/chkconfig app-base-core
/usr/sbin/addsudo /sbin/shutdown app-base-core
/usr/sbin/addsudo /sbin/service app-base-core
/usr/sbin/addsudo /usr/bin/api app-base-core
/usr/sbin/addsudo /usr/bin/file app-base-core
/usr/sbin/addsudo /usr/bin/find app-base-core
/usr/sbin/addsudo /usr/bin/tail app-base-core
/usr/sbin/addsudo /usr/bin/chfn app-base-core
/usr/sbin/addsudo /usr/bin/du app-base-core
/usr/sbin/addsudo /usr/bin/passwd app-base-core
/usr/sbin/addsudo /usr/sbin/app-passwd app-base-core
/usr/sbin/addsudo /usr/sbin/app-realpath app-base-core
/usr/sbin/addsudo /usr/sbin/app-rename app-base-core
/usr/sbin/addsudo /usr/sbin/userdel app-base-core
/usr/sbin/addsudo /usr/bin/yum app-base-core
/usr/sbin/addsudo /usr/bin/yum-config-manager app-base-core
/usr/sbin/addsudo /usr/sbin/yum-install app-base-core

# Import EPEL key
rpm --import /etc/pki/rpm-gpg/CLEAROS-RPM-GPG-KEY-EPEL-6  >/dev/null 2>&1

# TODO: move this to clearsync
LINE=`grep "^Cmnd_Alias CLEARSYNC" /etc/sudoers 2>/dev/null`
CHECK=`echo $LINE, | grep /usr/sbin/syncaction,`
if [ -z "$CHECK" ]; then
    ESCAPE=`echo /usr/sbin/syncaction | sed 's/\//\\\\\//g'`
    sed -i -e "s/Cmnd_Alias CLEARSYNC.*=/Cmnd_Alias CLEARSYNC = $ESCAPE,/i" /etc/sudoers
    sed -i -e "s/[[:space:]]*,[[:space:]]*$//i" /etc/sudoers
    chmod 440 /etc/sudoers
fi

# Reload clearsyncd 
# TODO: remove after version 7
#-----------------------------

logger -p local6.notice -t clearsync "base - clearsync configuration change detected"
/sbin/service clearsyncd condrestart >/dev/null 2>&1

# FIXME FIXME FIXME - beta only
/usr/bin/yum-config-manager --enable clearos-updates-testing >/dev/null 2>&1
