<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['base_category_cloud'] = 'Cloud';
$lang['base_category_gateway'] = 'Gateway';
$lang['base_category_network'] = 'Netzwerk';
$lang['base_category_reports'] = 'Berichte';
$lang['base_category_server'] = 'Server';
$lang['base_category_spotlight'] = 'Spotlight';
$lang['base_category_system'] = 'System';
$lang['base_subcategory_account_manager'] = 'Benutzerkontenverwaltung';
$lang['base_subcategory_accounts'] = 'Accounts';
$lang['base_subcategory_antimalware'] = 'Antimalware';
$lang['base_subcategory_applications'] = 'Applications';
$lang['base_subcategory_backup'] = 'Sicherung';
$lang['base_subcategory_bandwidth_control'] = 'Bandwidth Control';
$lang['base_subcategory_base'] = 'Base';
$lang['base_subcategory_communication_and_collaboration'] = 'Communication and Collaboration';
$lang['base_subcategory_configuration'] = 'Einstellungen';
$lang['base_subcategory_content_filter_and_proxy'] = 'Webfilter und Proxy';
$lang['base_subcategory_content_management_systems'] = 'Content Management Systems';
$lang['base_subcategory_database'] = 'Datenbanken';
$lang['base_subcategory_device_management'] = 'Device Management';
$lang['base_subcategory_directory'] = 'Verzeichnisdienst';
$lang['base_subcategory_file'] = 'Dateien';
$lang['base_subcategory_filtering'] = 'Filtering';
$lang['base_subcategory_firewall'] = 'Firewall';
$lang['base_subcategory_infrastructure'] = 'Netzwerkinfrastruktur';
$lang['base_subcategory_intrusion_protection'] = 'Einbruchsschutz';
$lang['base_subcategory_mail'] = 'E-Mail';
$lang['base_subcategory_messaging'] = 'Messaging';
$lang['base_subcategory_monitoring'] = 'Monitoring';
$lang['base_subcategory_my_account'] = 'Mein Konto';
$lang['base_subcategory_network_infrastructure'] = 'Network Infrastructure';
$lang['base_subcategory_performance_and_resources'] = 'Performance and Resources';
$lang['base_subcategory_print'] = 'Drucken';
$lang['base_subcategory_protocol_filter'] = 'Protokoll Filter';
$lang['base_subcategory_resources'] = 'Ressourcen';
$lang['base_subcategory_security'] = 'Sicherheit';
$lang['base_subcategory_services'] = 'Services';
$lang['base_subcategory_settings'] = 'Einstellungen';
$lang['base_subcategory_storage'] = 'Speicher';
$lang['base_subcategory_updates'] = 'Updates';
$lang['base_subcategory_user_management'] = 'User Management';
$lang['base_subcategory_vpn'] = 'VPNs';
$lang['base_subcategory_web'] = 'Web';
