<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['base_category_cloud'] = 'Cloud';
$lang['base_category_gateway'] = 'Gateway';
$lang['base_category_my_account'] = 'Mein Konto';
$lang['base_category_network'] = 'Netzwerk';
$lang['base_category_reports'] = 'Berichte';
$lang['base_category_server'] = 'Server';
$lang['base_category_spotlight'] = 'Spotlight';
$lang['base_category_system'] = 'System';
$lang['base_subcategory_accounts'] = 'Accounts';
$lang['base_subcategory_accounts_manager'] = 'Benutzerkontenverwaltung';
$lang['base_subcategory_antimalware'] = 'Antimalware';
$lang['base_subcategory_backup'] = 'Sicherung';
$lang['base_subcategory_bandwidth_and_qos'] = 'Bandbreite und QoS';
$lang['base_subcategory_configuration'] = 'Einstellungen';
$lang['base_subcategory_content_filter_and_proxy'] = 'Webfilter und Proxy';
$lang['base_subcategory_dashboard'] = 'Dashboard';
$lang['base_subcategory_database'] = 'Datenbanken';
$lang['base_subcategory_directory'] = 'Verzeichnisdienst';
$lang['base_subcategory_file'] = 'Dateien';
$lang['base_subcategory_firewall'] = 'Firewall';
$lang['base_subcategory_infrastructure'] = 'Netzwerkinfrastruktur';
$lang['base_subcategory_intrusion_protection'] = 'Einbruchsschutz';
$lang['base_subcategory_mail'] = 'E-Mail';
$lang['base_subcategory_mail_scanning'] = 'E-Mail Überprüfung';
$lang['base_subcategory_messaging_and_collaboration'] = 'Datentransfer und Zusammenarbeit';
$lang['base_subcategory_monitoring'] = 'Monitoring';
$lang['base_subcategory_operating_system'] = 'Betriebssystem';
$lang['base_subcategory_overview'] = 'Übersicht';
$lang['base_subcategory_print'] = 'Drucken';
$lang['base_subcategory_protocol_filter'] = 'Protokoll Filter';
$lang['base_subcategory_resources'] = 'Ressourcen';
$lang['base_subcategory_security'] = 'Sicherheit';
$lang['base_subcategory_settings'] = 'Einstellungen';
$lang['base_subcategory_storage'] = 'Speicher';
$lang['base_subcategory_virtualization'] = 'Virtualization';
$lang['base_subcategory_vpn'] = 'VPNs';
$lang['base_subcategory_web'] = 'Web';
