<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['base_category_cloud'] = 'Cloud';
$lang['base_category_gateway'] = 'Gateway';
$lang['base_category_my_account'] = 'Minha Conta';
$lang['base_category_network'] = 'Rede';
$lang['base_category_reports'] = 'Relatórios';
$lang['base_category_server'] = 'Servidor';
$lang['base_category_spotlight'] = 'Spotlight';
$lang['base_category_system'] = 'Sistema';
$lang['base_subcategory_accounts'] = 'Conta';
$lang['base_subcategory_accounts_manager'] = 'Gerenciador de Contas';
$lang['base_subcategory_antimalware'] = 'Anti-malware';
$lang['base_subcategory_backup'] = 'Backup';
$lang['base_subcategory_bandwidth_and_qos'] = 'Largura de banda e QoS';
$lang['base_subcategory_configuration'] = 'Configuração';
$lang['base_subcategory_content_filter_and_proxy'] = 'Filtro de conteúdo e Proxy';
$lang['base_subcategory_dashboard'] = 'Painel de controle';
$lang['base_subcategory_database'] = 'banco de dados';
$lang['base_subcategory_directory'] = 'Diretório';
$lang['base_subcategory_file'] = 'Arquivo';
$lang['base_subcategory_firewall'] = 'Firewall';
$lang['base_subcategory_infrastructure'] = 'Infraestrutura';
$lang['base_subcategory_intrusion_protection'] = 'Proteção contra invasão';
$lang['base_subcategory_mail'] = 'Correio';
$lang['base_subcategory_mail_scanning'] = 'Análise de correio';
$lang['base_subcategory_messaging_and_collaboration'] = 'Mensagens e Colaboração';
$lang['base_subcategory_monitoring'] = 'Monitoring';
$lang['base_subcategory_operating_system'] = 'Sistema Operacional';
$lang['base_subcategory_overview'] = 'Visão Global';
$lang['base_subcategory_print'] = 'Imprimir';
$lang['base_subcategory_protocol_filter'] = 'Filtro de protocolo';
$lang['base_subcategory_resources'] = 'Recursos';
$lang['base_subcategory_security'] = 'Segurança';
$lang['base_subcategory_settings'] = 'Configurações';
$lang['base_subcategory_storage'] = 'Armazenamento';
$lang['base_subcategory_virtualization'] = 'Virtualization';
$lang['base_subcategory_vpn'] = 'VPN';
$lang['base_subcategory_web'] = 'Web';
