<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['base_category_cloud'] = 'Cloud';
$lang['base_category_gateway'] = 'Gateway';
$lang['base_category_network'] = 'Rede';
$lang['base_category_reports'] = 'Relatórios';
$lang['base_category_server'] = 'Servidor';
$lang['base_category_spotlight'] = 'Spotlight';
$lang['base_category_system'] = 'Sistema';
$lang['base_subcategory_account_manager'] = 'Account Manager';
$lang['base_subcategory_accounts'] = 'Conta';
$lang['base_subcategory_antimalware'] = 'Anti-malware';
$lang['base_subcategory_applications'] = 'Applications';
$lang['base_subcategory_backup'] = 'Backup';
$lang['base_subcategory_bandwidth_control'] = 'Bandwidth Control';
$lang['base_subcategory_base'] = 'Base';
$lang['base_subcategory_communication_and_collaboration'] = 'Communication and Collaboration';
$lang['base_subcategory_configuration'] = 'Configuração';
$lang['base_subcategory_content_filter_and_proxy'] = 'Filtro de conteúdo e Proxy';
$lang['base_subcategory_content_management_systems'] = 'Content Management Systems';
$lang['base_subcategory_database'] = 'banco de dados';
$lang['base_subcategory_device_management'] = 'Device Management';
$lang['base_subcategory_directory'] = 'Diretório';
$lang['base_subcategory_file'] = 'Arquivo';
$lang['base_subcategory_firewall'] = 'Firewall';
$lang['base_subcategory_infrastructure'] = 'Infraestrutura';
$lang['base_subcategory_intrusion_protection'] = 'Proteção contra invasão';
$lang['base_subcategory_mail'] = 'Correio';
$lang['base_subcategory_messaging'] = 'Messaging';
$lang['base_subcategory_monitoring'] = 'Monitoring';
$lang['base_subcategory_my_account'] = 'My Account';
$lang['base_subcategory_network_infrastructure'] = 'Network Infrastructure';
$lang['base_subcategory_performance_and_resources'] = 'Performance and Resources';
$lang['base_subcategory_print'] = 'Imprimir';
$lang['base_subcategory_protocol_filter'] = 'Filtro de protocolo';
$lang['base_subcategory_resources'] = 'Recursos';
$lang['base_subcategory_security'] = 'Segurança';
$lang['base_subcategory_services'] = 'Services';
$lang['base_subcategory_settings'] = 'Configurações';
$lang['base_subcategory_storage'] = 'Armazenamento';
$lang['base_subcategory_updates'] = 'Updates';
$lang['base_subcategory_user_management'] = 'User Management';
$lang['base_subcategory_vpn'] = 'VPN';
$lang['base_subcategory_web'] = 'Web';
