<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['base_category_cloud'] = 'Cloud';
$lang['base_category_gateway'] = 'Gateway (ထြက္ေပါက္)';
$lang['base_category_network'] = 'Network (ကြန္ယက္)';
$lang['base_category_reports'] = 'Reports (အစီရင္ခံစာ)';
$lang['base_category_server'] = 'Server (ဆာဗာ)';
$lang['base_category_spotlight'] = 'Spotlight (မီးေမာင္း)';
$lang['base_category_system'] = 'System (စနစ္)';
$lang['base_subcategory_account_manager'] = 'Account Manager';
$lang['base_subcategory_accounts'] = 'Accounts (လူစာရင္း)';
$lang['base_subcategory_antimalware'] = 'Antimalware (MalWare ဆန္႔က်င္မွဳ)';
$lang['base_subcategory_applications'] = 'Applications';
$lang['base_subcategory_backup'] = 'Backup (အရံအေထာက္အပံ့)';
$lang['base_subcategory_bandwidth_control'] = 'Bandwidth Control';
$lang['base_subcategory_base'] = 'Base';
$lang['base_subcategory_communication_and_collaboration'] = 'Communication and Collaboration';
$lang['base_subcategory_configuration'] = 'Configuration (အစီအစဥ္ခ်မွဳ)';
$lang['base_subcategory_content_filter_and_proxy'] = 'Content Filter and Proxy (အေၾကာင္းအရာစီစစ္မွဳနွင္႔ ကိုယ္စားလွယ္)';
$lang['base_subcategory_content_management_systems'] = 'Content Management Systems';
$lang['base_subcategory_database'] = 'Database (အခ်က္အလက္မ်ား)';
$lang['base_subcategory_device_management'] = 'Device Management';
$lang['base_subcategory_directory'] = 'Directory (လမ္းညႊန္)';
$lang['base_subcategory_file'] = 'File (ဖိုင္လ္)';
$lang['base_subcategory_firewall'] = 'Firewall (အရံအတား)';
$lang['base_subcategory_infrastructure'] = 'Infrastructure (အေျခခံ အေဆာက္အအံု။)';
$lang['base_subcategory_intrusion_protection'] = 'Intrusion Protection (အေႏွာင့္အယွက္ ကာကြယ္မွဳ)';
$lang['base_subcategory_mail'] = 'Mail (ေခ်ာစာ)';
$lang['base_subcategory_messaging'] = 'Messaging';
$lang['base_subcategory_monitoring'] = 'Monitoring';
$lang['base_subcategory_my_account'] = 'My Account';
$lang['base_subcategory_network_infrastructure'] = 'Network Infrastructure';
$lang['base_subcategory_performance_and_resources'] = 'Performance and Resources';
$lang['base_subcategory_print'] = '(Print) ပရင္႔ထုတ္ရန္';
$lang['base_subcategory_protocol_filter'] = 'Protocol Filter ( လမ္းေၾကာင္း စီစစ္မွဳ)';
$lang['base_subcategory_resources'] = 'Resources (အရင္းအျမစ္)';
$lang['base_subcategory_security'] = 'Security (လံုျခံဳမွဳ)';
$lang['base_subcategory_services'] = 'Services';
$lang['base_subcategory_settings'] = 'Settings (ခ်ိန္ညွိခ်က္)';
$lang['base_subcategory_storage'] = 'Storage (သိုေလွာင္ျခင္း)';
$lang['base_subcategory_updates'] = 'Updates';
$lang['base_subcategory_user_management'] = 'User Management';
$lang['base_subcategory_vpn'] = 'VPN (ဗြီပီအင္)';
$lang['base_subcategory_web'] = 'Web ( ၀ဘ္စာမ်က္နွာ)';
