<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['base_category_cloud'] = 'Cloud';
$lang['base_category_gateway'] = 'Gateway (ထြက္ေပါက္)';
$lang['base_category_my_account'] = 'မိမိအေကာင္႔';
$lang['base_category_network'] = 'Network (ကြန္ယက္)';
$lang['base_category_reports'] = 'Reports (အစီရင္ခံစာ)';
$lang['base_category_server'] = 'Server (ဆာဗာ)';
$lang['base_category_spotlight'] = 'Spotlight (မီးေမာင္း)';
$lang['base_category_system'] = 'System (စနစ္)';
$lang['base_subcategory_accounts'] = 'Accounts (လူစာရင္း)';
$lang['base_subcategory_accounts_manager'] = 'Accounts Manager (လူစာရင္း မန္ေနဂ်ာ)';
$lang['base_subcategory_antimalware'] = 'Antimalware (MalWare ဆန္႔က်င္မွဳ)';
$lang['base_subcategory_backup'] = 'Backup (အရံအေထာက္အပံ့)';
$lang['base_subcategory_bandwidth_and_qos'] = 'Bandwidth and QoS (အျမန္နွုန္းနွင္႔ ၀န္ေဆာင္မွဳအဆင္႔)';
$lang['base_subcategory_configuration'] = 'Configuration (အစီအစဥ္ခ်မွဳ)';
$lang['base_subcategory_content_filter_and_proxy'] = 'Content Filter and Proxy (အေၾကာင္းအရာစီစစ္မွဳနွင္႔ ကိုယ္စားလွယ္)';
$lang['base_subcategory_dashboard'] = 'Dashboard (ဒိုင္ခြက္)';
$lang['base_subcategory_database'] = 'Database (အခ်က္အလက္မ်ား)';
$lang['base_subcategory_directory'] = 'Directory (လမ္းညႊန္)';
$lang['base_subcategory_file'] = 'File (ဖိုင္လ္)';
$lang['base_subcategory_firewall'] = 'Firewall (အရံအတား)';
$lang['base_subcategory_infrastructure'] = 'Infrastructure (အေျခခံ အေဆာက္အအံု။)';
$lang['base_subcategory_intrusion_protection'] = 'Intrusion Protection (အေႏွာင့္အယွက္ ကာကြယ္မွဳ)';
$lang['base_subcategory_mail'] = 'Mail (ေခ်ာစာ)';
$lang['base_subcategory_mail_scanning'] = 'Mail Scanning (ေခ်ာစာ စစ္ၾကည္႔မွဳ)';
$lang['base_subcategory_messaging_and_collaboration'] = 'သတင္းပို႔ျခင္းနွင္႔ ပူေပါင္းေဆာင္ရြက္ျခင္း';
$lang['base_subcategory_monitoring'] = 'Monitoring';
$lang['base_subcategory_operating_system'] = 'လုပ္ငန္းလည္ပတ္မွဳစနစ္ (OS)';
$lang['base_subcategory_overview'] = 'ျခံဳငံုသံုးသပ္ခ်က္';
$lang['base_subcategory_print'] = '(Print) ပရင္႔ထုတ္ရန္';
$lang['base_subcategory_protocol_filter'] = 'Protocol Filter ( လမ္းေၾကာင္း စီစစ္မွဳ)';
$lang['base_subcategory_resources'] = 'Resources (အရင္းအျမစ္)';
$lang['base_subcategory_security'] = 'Security (လံုျခံဳမွဳ)';
$lang['base_subcategory_settings'] = 'Settings (ခ်ိန္ညွိခ်က္)';
$lang['base_subcategory_storage'] = 'Storage (သိုေလွာင္ျခင္း)';
$lang['base_subcategory_virtualization'] = 'Virtualization';
$lang['base_subcategory_vpn'] = 'VPN (ဗြီပီအင္)';
$lang['base_subcategory_web'] = 'Web ( ၀ဘ္စာမ်က္နွာ)';
