<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['base_category_cloud'] = 'Cloud';
$lang['base_category_gateway'] = '网关';
$lang['base_category_my_account'] = '我的帐户';
$lang['base_category_network'] = '网络';
$lang['base_category_reports'] = '报告';
$lang['base_category_server'] = '服务器';
$lang['base_category_spotlight'] = '焦点';
$lang['base_category_system'] = '系统';
$lang['base_subcategory_accounts'] = '帐户';
$lang['base_subcategory_accounts_manager'] = '帐户管理';
$lang['base_subcategory_antimalware'] = '反恶意软件';
$lang['base_subcategory_backup'] = '备份';
$lang['base_subcategory_bandwidth_and_qos'] = '带宽和QoS';
$lang['base_subcategory_configuration'] = '配置';
$lang['base_subcategory_content_filter_and_proxy'] = '内容过滤器和代理';
$lang['base_subcategory_dashboard'] = '数据报表';
$lang['base_subcategory_database'] = '数据库';
$lang['base_subcategory_directory'] = '目录';
$lang['base_subcategory_file'] = '文件';
$lang['base_subcategory_firewall'] = '防火墙';
$lang['base_subcategory_infrastructure'] = '基本设施';
$lang['base_subcategory_intrusion_protection'] = '入侵防御';
$lang['base_subcategory_mail'] = '邮件';
$lang['base_subcategory_mail_scanning'] = '邮件扫描';
$lang['base_subcategory_messaging_and_collaboration'] = '消息与协作';
$lang['base_subcategory_monitoring'] = 'Monitoring';
$lang['base_subcategory_operating_system'] = '操作系统';
$lang['base_subcategory_overview'] = '概览';
$lang['base_subcategory_print'] = '打印';
$lang['base_subcategory_protocol_filter'] = '协议过滤器';
$lang['base_subcategory_resources'] = '资源';
$lang['base_subcategory_security'] = '安全';
$lang['base_subcategory_settings'] = '设置';
$lang['base_subcategory_storage'] = '存储';
$lang['base_subcategory_virtualization'] = 'Virtualization';
$lang['base_subcategory_vpn'] = 'VPN';
$lang['base_subcategory_web'] = 'Web';
