<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['base_category_cloud'] = 'Cloud';
$lang['base_category_gateway'] = 'Gateway';
$lang['base_category_my_account'] = 'Mitt konto';
$lang['base_category_network'] = 'Nätverk';
$lang['base_category_reports'] = 'Rapporter';
$lang['base_category_server'] = 'Server';
$lang['base_category_spotlight'] = 'Spotlight';
$lang['base_category_system'] = 'System';
$lang['base_subcategory_accounts'] = 'Konton';
$lang['base_subcategory_accounts_manager'] = 'Kontohanterare';
$lang['base_subcategory_antimalware'] = 'Skydd mot skadlig kod';
$lang['base_subcategory_backup'] = 'Backup';
$lang['base_subcategory_bandwidth_and_qos'] = 'Bandbredd och QoS';
$lang['base_subcategory_configuration'] = 'Konfiguration';
$lang['base_subcategory_content_filter_and_proxy'] = 'Innehållsfilter och proxy';
$lang['base_subcategory_dashboard'] = 'Instrumentpanel';
$lang['base_subcategory_database'] = 'Databas';
$lang['base_subcategory_directory'] = 'Katalog';
$lang['base_subcategory_file'] = 'Fil';
$lang['base_subcategory_firewall'] = 'Brandvägg';
$lang['base_subcategory_infrastructure'] = 'Infrastruktur';
$lang['base_subcategory_intrusion_protection'] = 'Intrångsskydd';
$lang['base_subcategory_mail'] = 'E-post';
$lang['base_subcategory_mail_scanning'] = 'E-postsökning';
$lang['base_subcategory_messaging_and_collaboration'] = 'Meddelanden och samarbete';
$lang['base_subcategory_monitoring'] = 'Monitoring';
$lang['base_subcategory_operating_system'] = 'Operativsystem';
$lang['base_subcategory_overview'] = 'Översikt';
$lang['base_subcategory_print'] = 'Skriv ut';
$lang['base_subcategory_protocol_filter'] = 'Protokollfilter';
$lang['base_subcategory_resources'] = 'Källor';
$lang['base_subcategory_security'] = 'Säkerhet';
$lang['base_subcategory_settings'] = 'Inställningar';
$lang['base_subcategory_storage'] = 'Lagringsutrymme';
$lang['base_subcategory_virtualization'] = 'Virtualization';
$lang['base_subcategory_vpn'] = 'VPN';
$lang['base_subcategory_web'] = 'Webb';
