<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['base_category_cloud'] = 'Cloud';
$lang['base_category_gateway'] = 'Gateway';
$lang['base_category_network'] = 'Nätverk';
$lang['base_category_reports'] = 'Rapporter';
$lang['base_category_server'] = 'Server';
$lang['base_category_spotlight'] = 'Spotlight';
$lang['base_category_system'] = 'System';
$lang['base_subcategory_account_manager'] = 'Kontohanterare';
$lang['base_subcategory_accounts'] = 'Konton';
$lang['base_subcategory_antimalware'] = 'Skydd mot skadlig kod';
$lang['base_subcategory_applications'] = 'Applications';
$lang['base_subcategory_backup'] = 'Backup';
$lang['base_subcategory_bandwidth_control'] = 'Bandwidth Control';
$lang['base_subcategory_base'] = 'Base';
$lang['base_subcategory_communication_and_collaboration'] = 'Communication and Collaboration';
$lang['base_subcategory_configuration'] = 'Konfiguration';
$lang['base_subcategory_content_filter_and_proxy'] = 'Innehållsfilter och proxy';
$lang['base_subcategory_content_management_systems'] = 'Content Management Systems';
$lang['base_subcategory_database'] = 'Databas';
$lang['base_subcategory_device_management'] = 'Device Management';
$lang['base_subcategory_directory'] = 'Katalog';
$lang['base_subcategory_file'] = 'Fil';
$lang['base_subcategory_firewall'] = 'Brandvägg';
$lang['base_subcategory_infrastructure'] = 'Infrastruktur';
$lang['base_subcategory_intrusion_protection'] = 'Intrångsskydd';
$lang['base_subcategory_mail'] = 'E-post';
$lang['base_subcategory_messaging'] = 'Messaging';
$lang['base_subcategory_monitoring'] = 'Monitoring';
$lang['base_subcategory_my_account'] = 'Mitt konto';
$lang['base_subcategory_network_infrastructure'] = 'Network Infrastructure';
$lang['base_subcategory_performance_and_resources'] = 'Performance and Resources';
$lang['base_subcategory_print'] = 'Skriv ut';
$lang['base_subcategory_protocol_filter'] = 'Protokollfilter';
$lang['base_subcategory_resources'] = 'Källor';
$lang['base_subcategory_security'] = 'Säkerhet';
$lang['base_subcategory_services'] = 'Services';
$lang['base_subcategory_settings'] = 'Inställningar';
$lang['base_subcategory_storage'] = 'Lagringsutrymme';
$lang['base_subcategory_updates'] = 'Updates';
$lang['base_subcategory_user_management'] = 'User Management';
$lang['base_subcategory_vpn'] = 'VPN';
$lang['base_subcategory_web'] = 'Webb';
