#!/bin/sh

###############################################################################
# V A L I D A T E
###############################################################################

if [ -z "$1" ]; then
        echo "Usage: $0 <app>"
        exit 1
else
        COMMAND="$1"
fi

if [ -n "$2" ]; then
    FLAG=$2
    FLAG_LOG=" - $FLAG"
else
    FLAG=""
    FLAG_LOG=""
fi

###############################################################################
# M A I N
###############################################################################

if [ -x "/usr/clearos/apps/$1/deploy/syncaction" ]; then
        /usr/bin/logger -p local6.notice -t clearsync "$1 - event triggered$FLAG_LOG"
        /usr/clearos/apps/$1/deploy/syncaction "$FLAG"
else
        /usr/bin/logger -p local6.notice -t clearsync "$1 - no events defined"
fi
