#!/usr/bin/python -u
"""Webconfig YUM Helper

This is a YUM helper program which installs/removes Webconfig App RPMs

    --help, -h  Display this message.
    --install, -i   Install specified RPMs.
    --uninstall, -u Uninstall specified RPMs.

Examples:
    Install modules foo and bar:
    # wc-yum -i app-foo app-bar

    Uninstall modules foo and bar:
    # wc-yum --uninstall app-foo app-bar
"""
import os
import re
import sys
import yum
import rpm
import logging
import getopt
import json
import httplib
import urllib
import time
from urlparse import urlparse
from yum import Errors
from yum.callbacks import DownloadBaseCallback
from yum.callbacks import ProcessTransBaseCallback
from yum.rpmtrans import RPMBaseCallback
from yum.yumRepo import YumRepository as Repository
from xml.etree.ElementTree import parse

# Global status object
status = { 'code': 0, 'progress': 0, 'overall': 0, 'details': None, 'errmsg': None }

# Default SDN webservice URL
sdn_url = "secure.clearcenter.com"

# Default SDN repo request and method
sdn_request = "/ws/1.0/marketplace/"
sdn_method = "get_repo_list"

def wcLogger(msg, *k, **kw):
    pass

class wcTransactionCallback(ProcessTransBaseCallback):
    def __init__(self):
        ProcessTransBaseCallback.__init__(self)
        
    def event(self, state, data = None):
        if state in PT_MESSAGES.keys():
            status['details'] = PT_MESSAGES[state]
            print json.dumps(status)

class wcDownloadCallback(DownloadBaseCallback):
    def __init__(self, pkg_count):
        DownloadBaseCallback.__init__(self)
        self.pkg_index = 0
        self.pkg_count = pkg_count * 2

    def updateProgress(self, name, frac, fread, ftime):
        pct = int(frac * 100)
        if pct == 100:
            self.pkg_index = self.pkg_index + 1
        package = name.replace('.rpm', '')
        status['progress'] = pct
        status['details'] = "Downloading: %s" %(package)
        status['overall'] = int(self.pkg_index * 100 / self.pkg_count)
        print json.dumps(status)

class wcProgressCallback(RPMBaseCallback):
    def __init__(self, pkg_count):
        RPMBaseCallback.__init__(self)
        self.lastmsg = None
        self.lastpackage = None
        self.pkg_index = pkg_count
        self.pkg_count = pkg_count * 2

    def event(self, package, action, te_current, te_total, ts_current, ts_total):
        package = str.replace(str(package), ' ', '')
        if te_current == te_total:
            self.pkg_index = self.pkg_index + 1
        status['progress'] = int(te_current * 100 / te_total)
        status['overall'] = int(self.pkg_index * 100 / self.pkg_count)
        status['details'] = "%s: (%d/%d): %s" %(self.action[action], ts_current, ts_total, package)
        msg = "%s: %s" %(status['details'], status['progress'])
        if msg != self.lastmsg:
            print json.dumps(status)

        self.lastmsg = msg;
        self.lastpackage = package

    def scriptout(self, package, msgs):
        if msgs:
            print msgs,

class wcRepo:
    def __init__(self, arch):

        self.url = sdn_url
        self.request = sdn_request
        self.method = sdn_method
        self.basearch = arch

        if os.getenv('SDN_URL') != None:
            self.url = os.getenv('SDN_URL')
        if os.getenv('SDN_REQUEST') != None:
            self.request = os.getenv('SDN_REQUEST')
        if os.getenv('SDN_METHOD') != None:
            self.method = os.getenv('SDN_METHOD')

        self.organization_vendor = { 'clearcenter.com': 'clear' }

    def fetch(self):
        status['details'] = 'Fetching repositories.'
        print json.dumps(status)

        if os.path.exists('/var/clearos/registration/registered') == False:
            return []

        osvendor = None
        fh = open('/etc/product', 'r')
        lines = fh.readlines()
        fh.close()
        for line in lines:
            kv = self.parse_kv_line(line)
            if not kv.has_key('vendor'):
                continue
            osvendor = kv['vendor']
            break
        if osvendor == None:
            status['code'] = 3
            raise Exception('OS vendor not found.')

        hostkey = None
        suva_conf = parse(urllib.urlopen('file:///etc/suvad.conf')).getroot()
        for org in suva_conf.findall('organization'):
            if not self.organization_vendor.has_key(org.attrib.get('name')):
                continue
            if self.organization_vendor[org.attrib.get('name')] != osvendor:
                continue
            hostkey = org.findtext('hostkey')
            break

        if hostkey == None or hostkey == '00000000000000000000000000000000':
            status['code'] = 4
            raise Exception('system hostkey not found.')

        osname=None
        osversion=None
        fh = open('/etc/product', 'r')
        lines = fh.readlines()
        fh.close()
        for line in lines:
            kv = self.parse_kv_line(line)
            if not kv.has_key('name'):
                continue
            osname = kv['name']
            break
        if osname == None:
            status['code'] = 4
            raise Exception('OS name not found.')
        for line in lines:
            kv = self.parse_kv_line(line)
            if not kv.has_key('version'):
                continue
            osversion = kv['version']
            break
        if osversion == None:
            status['code'] = 6
            raise Exception('OS version not found.')

        params = {
            'method': self.method, 'hostkey': hostkey,
            'vendor': osvendor, 'osname': osname, 'osversion': osversion }
        request = "%s?%s" %(self.request, urllib.urlencode(params))

        hc = httplib.HTTPSConnection(self.url)
        hc.request("GET", request)
        hr = hc.getresponse()
        if hr.status != 200:
            status['code'] = 7
            raise Exception('unable to retrieve repository data.')

        buffer = hr.read()
        response = json.loads(buffer)
        if not response.has_key('code') or not response.has_key('repos'):
            status['code'] = 8
            raise Exception('malformed repository data response.')

        if response['code'] != 0:
            status['code'] = 9
            raise Exception('malformed repository data.')

        repos = []
        baseurl = False
        for r in response['repos']:
            repo = Repository(r['name'])
            urls = []
            for u in r['baseurl']:
                if len(u['username']) == 0:
                    url = u['url']
                else:
                    url = urlparse(u['url'])
                    port = 80
                    if url.port != None:
                        port = url.port
                    url = "%s://%s:%s@%s:%s%s" %(
                        url.scheme, u['username'], u['password'],
                        url.netloc, port, url.path)
                urls.append(str(url) + '/' + self.basearch)

            repo.setAttribute('baseurl', urls)
            repo.setAttribute('description', r['description'])
            repo.setAttribute('enabled', r['enabled'])
            repo.setAttribute('gpgcheck', r['gpgcheck'])
            repo.setAttribute('name', r['name'])
            repo.enable()
            repos.append(repo)
        return repos

    def parse_kv_line(self, line):
        kv = {}
        rx = re.compile(r'\s*(\w+)\s*=\s*(.*),?')
        for k,v in rx.findall(line):
            if v[-1] == '"':
                v = v[1:-1]
            if '=' in v:
                kv[k] = self.parse_kv_line(self, v)
            else:
                kv[k] = v.rstrip()
        return kv

class wcYumHelper(yum.YumBase):
    def __init__(self, pkgs):
        yum.YumBase.__init__(self)

        wc_repo = wcRepo(self.arch.basearch)
        for r in wc_repo.fetch():
            self.repos.add(r)

        installpkgs = []
        updatepkgs = []
        donothingpkgs = []

        self.conf.rpm_check_debug = False

        status['progress'] = 35
        status['details'] = 'Updating repositories and preparing package dependencies... this may take a few minutes.'
        print json.dumps(status)

        searchlist = ['name']
        matching = self.searchGenerator(searchlist, pkgs)

        for (po, matched_value) in matching:
            status['progress'] = 100
            status['overall'] = 1
            print json.dumps(status)

            if po.name not in pkgs:
                continue

            installedByKey = self.rpmdb.searchNevra(name=po.name)
            if len(installedByKey) == 0:
                if len(installpkgs) == 0:
                    installpkgs.append(po)
                    continue
                found = False
                for newpo in installpkgs:
                    if newpo.name == po.name:
                        found = True
                        if po.EVR > newpo.EVR:
                            installpkgs.remove(newpo)
                            installpkgs.append(po)
                if found == False:
                    installpkgs.append(po)
                continue

            for installed_pkg in installedByKey:
                if po.EVR > installed_pkg.EVR:
                    updatepkgs.append((po, installed_pkg))
                elif po.EVR == installed_pkg.EVR:
                    donothingpkgs.append(po)
                else:
                    donothingpkgs.append(po)

        for po in installpkgs:
            self.install(po)
        for (po, oldpo) in updatepkgs:
            self.tsInfo.addUpdate(po, oldpo)

        self.repos.setProgressBar(wcDownloadCallback(100))
        self.buildTransaction()
        if len(self.tsInfo) == 0:
            status['code'] = 1
            raise Exception("no packages selected for install.")

        self.processTransaction(None, None, wcProgressCallback(len(self.tsInfo)))
        status['overall'] = 100
        status['details'] = 'Installation complete.'
        print json.dumps(status)

class wcRpmHelper:
    def __init__(self):
        self.pkg_count = 0;
        self.pkg_index = 0;

    def transactionCallback(self, reason, amount, total, key, client_data):
        if reason == rpm.RPMCALLBACK_UNINST_START:
            status['progress'] = 0 
            status['overall'] = int(self.pkg_index * 100 / self.pkg_count)
            status['details'] = 'Uninstalling: (%d/%d): %s' %(self.pkg_index + 1, self.pkg_count, key)
            print json.dumps(status)
        if reason == rpm.RPMCALLBACK_UNINST_PROGRESS:
            status['progress'] = int(total * 100 / amount)
            status['details'] = 'Uninstalling: (%d/%d): %s' %(self.pkg_index + 1, self.pkg_count, key)
            print json.dumps(status)
        if reason == rpm.RPMCALLBACK_UNINST_STOP:
            status['progress'] = 100
            status['details'] = 'Uninstalled: (%d/%d): %s' %(self.pkg_index + 1, self.pkg_count, key)
            print json.dumps(status)

    def isPackageInstalled(self, pkg):
        ts = rpm.TransactionSet()
        mi = ts.dbMatch('name', pkg)
        try:
            for h in mi:
                return True
            return False
        except StopIteration:
            return False

    def removePackages(self, pkgs):
        self.pkg_index = 0
        self.pkg_count = len(pkgs)
        ts = rpm.TransactionSet()
        for pkg in pkgs:
            ts.addErase(pkg)
        unmet = ts.check()
        if len(unmet) > 0:
            status['code'] = 2
            status['details'] = unmet;
            raise Exception("unmet dependencies.")
        ts.order()
        ts.run(self.transactionCallback, 1)
        status['overall'] = 100
        status['details'] = 'Uninstall complete.'
        print json.dumps(status)

def main():
    mode = 0
    try:
        opts, args = getopt.getopt(sys.argv[1:], "hi:u:", ["help", "install", "uninstall"])
    except getopt.error, msg:
        print "Error, %s." % msg
        print "Try --help for usage."
        sys.exit(-1)
    pkgs = []
    for o, a in opts:
        if o in ("-h", "--help"):
            print __doc__
            sys.exit(1)
        if o in ("-i", "--install"):
            mode = 1
            pkgs.append(a)
        if o in ("-u", "--uninstall"):
            mode = 2
            pkgs.append(a)

    verbose_logger = logging.getLogger("yum.verbose.YumPlugins")
    setattr(verbose_logger, 'log', wcLogger)
    setattr(verbose_logger, 'info', wcLogger)
    setattr(verbose_logger, 'debug', wcLogger)
    setattr(verbose_logger, 'error', wcLogger)
    verbose_logger = logging.getLogger("yum.Errors")
    setattr(verbose_logger, 'log', wcLogger)
    setattr(verbose_logger, 'info', wcLogger)
    setattr(verbose_logger, 'debug', wcLogger)
    setattr(verbose_logger, 'error', wcLogger)

    if mode == 0:
        print "Error, no mode specified."
        print "Try --help for usage."
        sys.exit(-1)
    for a in args:
        pkgs.append(a)
    wc_rpm = wcRpmHelper()
    try:
        if mode == 1:
            wc_yum = wcYumHelper(pkgs)
        elif mode == 2:
            wc_rpm.removePackages(pkgs)
    except Errors.YumDownloadError, errstr:
        status['code'] = -1
        status['errmsg'] = "Exception: Errors were encountered while downloading"
        print json.dumps(status)
        sys.exit(-1)
    except Exception, msg:
        if status['code'] == 0:
            status['code'] = -1
            status['errmsg'] = "Exception: %s" %msg
        else:
            status['errmsg'] = "Error, %s" %msg
        print json.dumps(status)
        sys.exit(-1)
    sys.exit(0)

if __name__ == "__main__":
    main()

# vi: ts=4 syntax=python
