<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['base_category_cloud'] = 'Cloud';
$lang['base_category_gateway'] = 'Brama';
$lang['base_category_my_account'] = 'Moje konto';
$lang['base_category_network'] = 'Sieć';
$lang['base_category_reports'] = 'Raporty';
$lang['base_category_server'] = 'Serwer';
$lang['base_category_spotlight'] = 'Centrum uwagi';
$lang['base_category_system'] = 'System';
$lang['base_subcategory_accounts'] = 'Konta';
$lang['base_subcategory_accounts_manager'] = 'Menadżer kont';
$lang['base_subcategory_antimalware'] = 'Antimalware';
$lang['base_subcategory_backup'] = 'Kopia zapasowa';
$lang['base_subcategory_bandwidth_and_qos'] = 'Pasmo i QoS';
$lang['base_subcategory_configuration'] = 'Konfiguracja';
$lang['base_subcategory_content_filter_and_proxy'] = 'Filtr zawartości i Proxy';
$lang['base_subcategory_dashboard'] = 'Panel informacyjny';
$lang['base_subcategory_database'] = 'Baza danych';
$lang['base_subcategory_directory'] = 'Katalog';
$lang['base_subcategory_file'] = 'Plik';
$lang['base_subcategory_firewall'] = 'Zapora sieciowa';
$lang['base_subcategory_infrastructure'] = 'Infrastruktura';
$lang['base_subcategory_intrusion_protection'] = 'Ochrona przed intruzami';
$lang['base_subcategory_mail'] = 'Poczta';
$lang['base_subcategory_mail_scanning'] = 'Skanowanie poczty';
$lang['base_subcategory_messaging_and_collaboration'] = 'Korespondencja i współpraca';
$lang['base_subcategory_monitoring'] = 'Monitoring';
$lang['base_subcategory_operating_system'] = 'System operacyjny';
$lang['base_subcategory_overview'] = 'Przegląd';
$lang['base_subcategory_print'] = 'Drukuj';
$lang['base_subcategory_protocol_filter'] = 'Filtr protokołów';
$lang['base_subcategory_resources'] = 'Zasoby';
$lang['base_subcategory_security'] = 'Ochrona';
$lang['base_subcategory_settings'] = 'Ustawienia';
$lang['base_subcategory_storage'] = 'Magazyn danych';
$lang['base_subcategory_virtualization'] = 'Virtualization';
$lang['base_subcategory_vpn'] = 'VPN';
$lang['base_subcategory_web'] = 'Sieć WWW';
