<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['base_category_cloud'] = 'Chmura';
$lang['base_category_gateway'] = 'Brama';
$lang['base_category_network'] = 'Sieć';
$lang['base_category_reports'] = 'Raporty';
$lang['base_category_server'] = 'Serwer';
$lang['base_category_spotlight'] = 'Centrum uwagi';
$lang['base_category_system'] = 'System';
$lang['base_subcategory_account_manager'] = 'Account Manager';
$lang['base_subcategory_accounts'] = 'Konta';
$lang['base_subcategory_antimalware'] = 'Antimalware';
$lang['base_subcategory_applications'] = 'Applications';
$lang['base_subcategory_backup'] = 'Kopia zapasowa';
$lang['base_subcategory_bandwidth_control'] = 'Bandwidth Control';
$lang['base_subcategory_base'] = 'Base';
$lang['base_subcategory_communication_and_collaboration'] = 'Communication and Collaboration';
$lang['base_subcategory_configuration'] = 'Konfiguracja';
$lang['base_subcategory_content_filter_and_proxy'] = 'Filtr zawartości i Proxy';
$lang['base_subcategory_content_management_systems'] = 'Content Management Systems';
$lang['base_subcategory_database'] = 'Baza danych';
$lang['base_subcategory_device_management'] = 'Device Management';
$lang['base_subcategory_directory'] = 'Katalog';
$lang['base_subcategory_file'] = 'Plik';
$lang['base_subcategory_firewall'] = 'Zapora sieciowa';
$lang['base_subcategory_infrastructure'] = 'Infrastruktura';
$lang['base_subcategory_intrusion_protection'] = 'Ochrona przed intruzami';
$lang['base_subcategory_mail'] = 'Poczta';
$lang['base_subcategory_messaging'] = 'Messaging';
$lang['base_subcategory_monitoring'] = 'Monitorowanie';
$lang['base_subcategory_my_account'] = 'My Account';
$lang['base_subcategory_network_infrastructure'] = 'Network Infrastructure';
$lang['base_subcategory_performance_and_resources'] = 'Performance and Resources';
$lang['base_subcategory_print'] = 'Drukuj';
$lang['base_subcategory_protocol_filter'] = 'Filtr protokołów';
$lang['base_subcategory_resources'] = 'Zasoby';
$lang['base_subcategory_security'] = 'Ochrona';
$lang['base_subcategory_services'] = 'Services';
$lang['base_subcategory_settings'] = 'Ustawienia';
$lang['base_subcategory_storage'] = 'Magazyn danych';
$lang['base_subcategory_updates'] = 'Updates';
$lang['base_subcategory_user_management'] = 'User Management';
$lang['base_subcategory_vpn'] = 'VPN';
$lang['base_subcategory_web'] = 'Sieć WWW';
